<a href="https://colab.research.google.com/github/gkhamis04/George-Khamis/blob/main/Vehicle_Count_Prediction_From_Sensor_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
import os

files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

print("Done 🚀")

Saving kaggle.json to kaggle (1).json
Done 🚀

In [2]:
import kagglehub

path = kagglehub.dataset_download("subho117/vehicle-count-prediction-from-sensor-data")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'vehicle-count-prediction-from-sensor-data' dataset.
Path to dataset files: /kaggle/input/vehicle-count-prediction-from-sensor-data

In [3]:
import os
import shutil

shutil.copytree(path, "./data", dirs_exist_ok=True)
print("Done! 🚀")

Done! 🚀

In [7]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv('/content/data/vehicles.csv')
df.head()

              DateTime  Vehicles
0  2015-11-01 00:00:00        15
1  2015-11-01 01:00:00        13
2  2015-11-01 02:00:00        10
3  2015-11-01 03:00:00         7
4  2015-11-01 04:00:00         9

In [5]:
df["DateTime"] = pd.to_datetime(df["DateTime"])
df["date"] = df["DateTime"].dt.day
df["weekday"] = df["DateTime"].dt.weekday
df["hour"] = df["DateTime"].dt.hour
df["month"] = df["DateTime"].dt.month
df["year"] = df["DateTime"].dt.year
df["dayofyear"] = df["DateTime"].dt.dayofyear
df["weekofyear"] = df["DateTime"].dt.isocalendar().week

df.head()

,DateTime,Vehicles,date,weekday,hour,month,year,dayofyear,weekofyear
0,2015-11-01 00:00:00,15,1,6,0,11,2015,305,44
1,2015-11-01 01:00:00,13,1,6,1,11,2015,305,44
2,2015-11-01 02:00:00,10,1,6,2,11,2015,305,44
3,2015-11-01 03:00:00,7,1,6,3,11,2015,305,44
4,2015-11-01 04:00:00,9,1,6,4,11,2015,305,44

In [6]:
df = df.drop(['DateTime'], axis=1)
train = df.drop(['Vehicles'], axis=1)
target = df['Vehicles']
print(train.head())
target.head()

   date  weekday  hour  month  year  dayofyear  weekofyear
0     1        6     0     11  2015        305          44
1     1        6     1     11  2015        305          44
2     1        6     2     11  2015        305          44
3     1        6     3     11  2015        305          44
4     1        6     4     11  2015        305          44

0    15
1    13
2    10
3     7
4     9
Name: Vehicles, dtype: int64

In [9]:
m1=RandomForestRegressor()
m1.fit(train,target)
m1.predict([[11,6,0,1,2015,11,2]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([9.12275])